# Generated by Django 4.0.4 on 2022-05-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compromisso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=20),
        ),
    ]
